### ISSUE TITLE
Dialyzer Error

### ISSUE THREAD

**Issue by christianjgreen** [kipcole9/cldr_numbers#9]
Howdy 🤠 and thanks for maintaining this great project. 

When `cldr_numbers` is included in our build with the core `cldr` application, the following errors are returned by dialyzer: 
```
lib/number/rbnf/processor.ex:371:pattern_match
The pattern
{:ok, _}

can never match the type
{:error, {atom(), binary()}}
________________________________________________________________________________
lib/cldr.ex:1:invalid_contract
Invalid type specification for function.

Function:
CoreAPI.Cldr.Number.Format.all_formats_for!/1

Success typing:
@spec all_formats_for!(binary() | %Cldr.LanguageTag{:cldr_locale_name => <<_::16, _::size(16)>>, _ => _}) :: %{
  :latn => %Cldr.Number.Format{
    :accounting => <<_::96, _::size(88)>>,
    :currency => <<_::80, _::size(16)>>,
    :currency_long => map(),
    :currency_short => [any(), ...],
    :currency_spacing => map(),
    :decimal_long => [any(), ...],
    :decimal_short => [any(), ...],
    :other => map(),
    :percent => <<_::48>>,
    :scientific => <<_::24>>,
    :standard => <<_::72>>
  }
}
________________________________________________________________________________
lib/cldr.ex:1:invalid_contract
Invalid type specification for function.

Function:
CoreAPI.Cldr.Number.Format.currency_spacing/2

Success typing:
@spec currency_spacing(
  binary()
  | %Cldr.LanguageTag{
      :canonical_locale_name => binary(),
      :cldr_locale_name => nil | binary(),
      :extensions => %{},
      :gettext_locale_name => _,
      :language => binary(),
      :language_subtags => [binary()],
      :language_variant => nil | binary(),
      :locale => %{},
      :private_use => [binary()],
      :rbnf_locale_name => binary(),
      :requested_locale_name => binary(),
      :script => nil | binary(),
      :territory => nil | binary(),
      :transform => %{}
    },
  atom() | binary()
) :: {:error, {atom(), binary()}}
```

**Comment by kipcole9** [comment]
Thanks for the report. I’ll dive into this in the next 24 hours.  Assuming dialyzer and me are one speaking terms it shouldn’t be too hard to resolve and I have a point release pending I’ll build it into.

**Comment by erikreedstrom** [comment]
> Assuming dialyzer and me are on speaking terms

🤣 🤣 🤣 🤣 

By the way, thanks for always being super responsive @kipcole9 !

**Comment by kipcole9** [comment]
OK, so its a little more challenging.  I've fixed a number of dialyse errors in [this commit](https://github.com/kipcole9/cldr_numbers/commit/7f31f2cb7d9d40b71e0c0354c6c62568e02eb185) and [this one](https://github.com/kipcole9/cldr_numbers/commit/12cccb3bde8780e8e3edc799ae2b3d18c9022bd7). I believe I have fixed:

* `CoreAPI.Cldr.Number.Format.currency_spacing/2` dialyzer error
* `CoreAPI.Cldr.Number.Format.all_formats_for!/1` dialyzer error

The error `lib/number/rbnf/processor.ex:371:pattern_match` seems spurious to me. The is a default `else` clause on a `with` macro.  Anyway, I've [posted on Elixir Forum](https://elixirforum.com/t/help-with-dialyzer-output/15202/9) in the hope of getting this resolved.  I suspect its related to generated code.

In running Dialyzer on the master branch I also see issues in `ex_cldr` and `ex_cldr_currencies` that I'll also have to fix.

**Comment by kipcole9** [comment]
Thanks too for the encouragement. I try to support these libs as if I was a consumer of them and therefore I do try to get problems solved quickly and properly.

**Comment by kipcole9** [comment]
Status update:
* `ex_cldr` now dialyzer warning free!
* `ex_cldr_currencies` has 3 more to go
* `ex_cldr_numbers` has a few but many of them are repetition

I will finally get these three projects dialyzer silent :-)  Probably another 24 hours it will take I'm afraid.

**Comment by kipcole9** [comment]
Best as I can tell its good to go now with no dialyzer warnings.  Please do:
```
mix deps.update ex_cldr ex_cldr_currencies ex_cldr_numbers
```
This should give you the following versions:
```
* ex_cldr 2.3.1 (Hex package) (mix)
* ex_cldr_currencies 2.2.3 (Hex package) (mix)
* ex_cldr_numbers 2.4.1 (Hex package) (mix)
```
Let me know if you see any other issues?

**Comment by christianjgreen** [comment]
Sorry for the late reply! Great work, they seem to be just about cleaned up.

The only errors I seem to still be getting are:

```
:0:unknown_type
Unknown type: Cldr.Locale.name/0.
________________________________________________________________________________
:0:unknown_type
Unknown type: List.t/0.
________________________________________________________________________________
:0:unknown_type
Unknown type: Map.t/0.
________________________________________________________________________________
```

**Comment by kipcole9** [comment]
Now dialyse is just plan irritating me :-). 

I thought I was completely clean!    But I think that's from [ex_cldr_lists](httpsL//github.com/kipcole9/cldr_lists] so perhaps I didn't clean it up (If I recall I may have only cleaned up ex_cldr, ex_cldr_numbers and ex_cldr_currencies).  Any other of the `cldr_*` packages you're using that I should also revisit?

I'll get cracking on it.

**Comment by christianjgreen** [comment]
Besides `ex_cldr_lists` the only thing we are using is `cldr_util` but I believe that one is clean.

Thanks again for sorting this out 🍾

**Comment by kipcole9** [comment]
Updated and I believe fixed. Please run:
```
mix deps.update ex_cldr ex_cldr_numbers ex_cldr_currencies ex_cldr_lists
```
Yep, I ended up all the way down the rabbit hole but found a `@spec` error in `Cldr.validate_locale/1` which is about as fundamental as things get in `Cldr.*` so it was worth the pain of updating almost everything :-)

Let me know if you see any other issues and thanks for the ongoing support to make this project a solid foundation for the community.

**Comment by christianjgreen** [comment]
It's as clean as can be! You rock 👍

**Comment by kipcole9** [comment]
Super happy to close this issue with a good outcome.  Thanks for the patience on this.  I learnt a lot about how dialyzer "thinks" which I suppose is a good thing as well :-)
